"""tournaments friendships analytics

Revision ID: 11ea81e06610
Revises: 5652a17146eb
Create Date: 2026-08-15 01:31:55.729861
"""
from alembic import op
import sqlalchemy as sa


revision = '11ea81e06610'
down_revision = '5652a17146eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('client_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_event_user_id'), 'analytics_event', ['user_id'], unique=False)
    op.create_index('ix_analytics_name_received', 'analytics_event', ['name', 'received_at'], unique=False)
    op.create_table('friend_code',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_friend_code_code'), 'friend_code', ['code'], unique=True)
    op.create_table('friendship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('addressee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['addressee_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'addressee_id', name='uq_friendship_pair')
    )
    op.create_index('ix_friendship_addressee', 'friendship', ['addressee_id', 'status'], unique=False)
    op.create_index(op.f('ix_friendship_requester_id'), 'friendship', ['requester_id'], unique=False)
    op.create_table('career_tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('career_athlete_id', sa.Integer(), nullable=False),
    sa.Column('event_code', sa.String(length=64), nullable=False),
    sa.Column('current_round', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('final_position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['career_athlete_id'], ['career_athlete.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_career_tournament_athlete', 'career_tournament', ['career_athlete_id', 'status'], unique=False)
    op.create_index(op.f('ix_career_tournament_career_athlete_id'), 'career_tournament', ['career_athlete_id'], unique=False)
    op.create_table('tournament_round',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('round_name', sa.String(length=16), nullable=False),
    sa.Column('field', sa.JSON(), nullable=False),
    sa.Column('player_result_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('advanced', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_result_id'], ['game_result.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['career_tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournament_round_tournament_id'), 'tournament_round', ['tournament_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tournament_round_tournament_id'), table_name='tournament_round')
    op.drop_table('tournament_round')
    op.drop_index(op.f('ix_career_tournament_career_athlete_id'), table_name='career_tournament')
    op.drop_index('ix_career_tournament_athlete', table_name='career_tournament')
    op.drop_table('career_tournament')
    op.drop_index(op.f('ix_friendship_requester_id'), table_name='friendship')
    op.drop_index('ix_friendship_addressee', table_name='friendship')
    op.drop_table('friendship')
    op.drop_index(op.f('ix_friend_code_code'), table_name='friend_code')
    op.drop_table('friend_code')
    op.drop_index('ix_analytics_name_received', table_name='analytics_event')
    op.drop_index(op.f('ix_analytics_event_user_id'), table_name='analytics_event')
    op.drop_table('analytics_event')
    # ### end Alembic commands ###
