"""sprint 6 media notifications

Revision ID: 155839d83817
Revises: 4ed5ee167571
Create Date: 2026-08-10 10:41:00.579856
"""
from alembic import op
import sqlalchemy as sa


revision = '155839d83817'
down_revision = '4ed5ee167571'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=128), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dedupe_key', name='uq_notification_dedupe')
    )
    op.create_index(op.f('ix_notification_kind'), 'notification', ['kind'], unique=False)
    op.create_index('ix_notification_user_created', 'notification', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_table('media_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.String(length=1000), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=1000), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['edition_id'], ['competition_edition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_media_source_external')
    )
    op.create_index(op.f('ix_media_item_edition_id'), 'media_item', ['edition_id'], unique=False)
    op.create_index(op.f('ix_media_item_kind'), 'media_item', ['kind'], unique=False)
    op.create_index(op.f('ix_media_item_published_at'), 'media_item', ['published_at'], unique=False)
    op.create_index(op.f('ix_media_item_source'), 'media_item', ['source'], unique=False)
    op.create_index('ix_media_kind_published', 'media_item', ['kind', 'published_at'], unique=False)
    op.create_table('media_athlete',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['media_item.id'], ),
    sa.PrimaryKeyConstraint('media_id', 'athlete_id')
    )
    op.create_table('media_country',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['media_item.id'], ),
    sa.PrimaryKeyConstraint('media_id', 'country_id')
    )
    op.create_table('media_sport',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_item.id'], ),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.id'], ),
    sa.PrimaryKeyConstraint('media_id', 'sport_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_sport')
    op.drop_table('media_country')
    op.drop_table('media_athlete')
    op.drop_index('ix_media_kind_published', table_name='media_item')
    op.drop_index(op.f('ix_media_item_source'), table_name='media_item')
    op.drop_index(op.f('ix_media_item_published_at'), table_name='media_item')
    op.drop_index(op.f('ix_media_item_kind'), table_name='media_item')
    op.drop_index(op.f('ix_media_item_edition_id'), table_name='media_item')
    op.drop_table('media_item')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_index('ix_notification_user_created', table_name='notification')
    op.drop_index(op.f('ix_notification_kind'), table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
