"""sprint 5 games engine

Revision ID: 4ed5ee167571
Revises: f56594cb1864
Create Date: 2026-08-10 10:29:44.646864
"""
from alembic import op
import sqlalchemy as sa


revision = '4ed5ee167571'
down_revision = 'f56594cb1864'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('tagline', sa.String(length=200), nullable=True),
    sa.Column('engine', sa.String(length=16), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('score_direction', sa.String(length=16), nullable=False),
    sa.Column('score_unit', sa.String(length=16), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_code'), 'game', ['code'], unique=True)
    op.create_index(op.f('ix_game_sport_id'), 'game', ['sport_id'], unique=False)
    op.create_table('user_progress',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('sessions_played', sa.Integer(), nullable=False),
    sa.Column('last_played_on', sa.Date(), nullable=True),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('trigger', sa.String(length=24), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievement_code'), 'achievement', ['code'], unique=True)
    op.create_table('game_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('xp_awarded', sa.Integer(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('played_on', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_session_game_id'), 'game_session', ['game_id'], unique=False)
    op.create_index('ix_game_session_leaderboard', 'game_session', ['game_id', 'score'], unique=False)
    op.create_index(op.f('ix_game_session_played_on'), 'game_session', ['played_on'], unique=False)
    op.create_index('ix_game_session_user', 'game_session', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_game_session_user_id'), 'game_session', ['user_id'], unique=False)
    op.create_table('user_achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement')
    )
    op.create_index(op.f('ix_user_achievement_user_id'), 'user_achievement', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_achievement_user_id'), table_name='user_achievement')
    op.drop_table('user_achievement')
    op.drop_index(op.f('ix_game_session_user_id'), table_name='game_session')
    op.drop_index('ix_game_session_user', table_name='game_session')
    op.drop_index(op.f('ix_game_session_played_on'), table_name='game_session')
    op.drop_index('ix_game_session_leaderboard', table_name='game_session')
    op.drop_index(op.f('ix_game_session_game_id'), table_name='game_session')
    op.drop_table('game_session')
    op.drop_index(op.f('ix_achievement_code'), table_name='achievement')
    op.drop_table('achievement')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_game_sport_id'), table_name='game')
    op.drop_index(op.f('ix_game_code'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
