"""sprint 3 personalization

Revision ID: 658d2f20dfae
Revises: b7f21c9d4e10
Create Date: 2026-08-10 09:27:40.048129
"""
from alembic import op
import sqlalchemy as sa


revision = '658d2f20dfae'
down_revision = 'b7f21c9d4e10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kind', name='uq_notification_preference')
    )
    op.create_index(op.f('ix_notification_preference_user_id'), 'notification_preference', ['user_id'], unique=False)
    op.create_table('user_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_user_preference')
    )
    op.create_index(op.f('ix_user_preference_user_id'), 'user_preference', ['user_id'], unique=False)
    op.create_index(op.f('ix_favorite_entity_type'), 'favorite', ['entity_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorite_entity_type'), table_name='favorite')
    op.drop_index(op.f('ix_user_preference_user_id'), table_name='user_preference')
    op.drop_table('user_preference')
    op.drop_index(op.f('ix_notification_preference_user_id'), table_name='notification_preference')
    op.drop_table('notification_preference')
    # ### end Alembic commands ###
