"""unique tournament round per name

Revision ID: 8dd03448307d
Revises: 11ea81e06610
Create Date: 2026-08-15 02:03:42.972176
"""
from alembic import op
import sqlalchemy as sa


revision = '8dd03448307d'
down_revision = '11ea81e06610'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_tournament_round', 'tournament_round', ['tournament_id', 'round_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tournament_round', 'tournament_round', type_='unique')
    # ### end Alembic commands ###
