"""sprint 1 foundation

Revision ID: e484c7c0228c
Revises: 
Create Date: 2026-08-09 17:34:52.758709
"""
from alembic import op
import sqlalchemy as sa


revision = 'e484c7c0228c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=96), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iso3', sa.String(length=3), nullable=False),
    sa.Column('iso2', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('flag_emoji', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_iso3'), 'country', ['iso3'], unique=True)
    op.create_table('sport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sport_category'), 'sport', ['category'], unique=False)
    op.create_index(op.f('ix_sport_code'), 'sport', ['code'], unique=True)
    op.create_table('athlete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('given_name', sa.String(length=96), nullable=False),
    sa.Column('family_name', sa.String(length=96), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('headshot_url', sa.String(length=512), nullable=True),
    sa.Column('bio', sa.String(length=2000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athlete_country_id'), 'athlete', ['country_id'], unique=False)
    op.create_index(op.f('ix_athlete_slug'), 'athlete', ['slug'], unique=True)
    op.create_table('competition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competition_level'), 'competition', ['level'], unique=False)
    op.create_index(op.f('ix_competition_slug'), 'competition', ['slug'], unique=True)
    op.create_index(op.f('ix_competition_sport_id'), 'competition', ['sport_id'], unique=False)
    op.create_table('discipline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport_id', 'code', name='uq_discipline_sport_code')
    )
    op.create_index(op.f('ix_discipline_sport_id'), 'discipline', ['sport_id'], unique=False)
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=16), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entity_type', 'entity_id', name='uq_favorite')
    )
    op.create_index(op.f('ix_favorite_user_id'), 'favorite', ['user_id'], unique=False)
    op.create_table('athlete_discipline',
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['discipline_id'], ['discipline.id'], ),
    sa.PrimaryKeyConstraint('athlete_id', 'discipline_id')
    )
    op.create_table('competition_edition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('host_city', sa.String(length=128), nullable=True),
    sa.Column('host_country_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.ForeignKeyConstraint(['host_country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'label', name='uq_edition_label')
    )
    op.create_index(op.f('ix_competition_edition_competition_id'), 'competition_edition', ['competition_id'], unique=False)
    op.create_index(op.f('ix_competition_edition_status'), 'competition_edition', ['status'], unique=False)
    op.create_index(op.f('ix_competition_edition_year'), 'competition_edition', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competition_edition_year'), table_name='competition_edition')
    op.drop_index(op.f('ix_competition_edition_status'), table_name='competition_edition')
    op.drop_index(op.f('ix_competition_edition_competition_id'), table_name='competition_edition')
    op.drop_table('competition_edition')
    op.drop_table('athlete_discipline')
    op.drop_index(op.f('ix_favorite_user_id'), table_name='favorite')
    op.drop_table('favorite')
    op.drop_index(op.f('ix_discipline_sport_id'), table_name='discipline')
    op.drop_table('discipline')
    op.drop_index(op.f('ix_competition_sport_id'), table_name='competition')
    op.drop_index(op.f('ix_competition_slug'), table_name='competition')
    op.drop_index(op.f('ix_competition_level'), table_name='competition')
    op.drop_table('competition')
    op.drop_index(op.f('ix_athlete_slug'), table_name='athlete')
    op.drop_index(op.f('ix_athlete_country_id'), table_name='athlete')
    op.drop_table('athlete')
    op.drop_index(op.f('ix_sport_code'), table_name='sport')
    op.drop_index(op.f('ix_sport_category'), table_name='sport')
    op.drop_table('sport')
    op.drop_index(op.f('ix_country_iso3'), table_name='country')
    op.drop_table('country')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
