"""sprint 4 rankings records medals

Revision ID: f56594cb1864
Revises: 658d2f20dfae
Create Date: 2026-08-10 10:10:56.139929
"""
from alembic import op
import sqlalchemy as sa


revision = 'f56594cb1864'
down_revision = '658d2f20dfae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport_id', 'name', name='uq_team_sport_name')
    )
    op.create_index(op.f('ix_team_country_id'), 'team', ['country_id'], unique=False)
    op.create_index(op.f('ix_team_sport_id'), 'team', ['sport_id'], unique=False)
    op.create_table('venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venue_country_id'), 'venue', ['country_id'], unique=False)
    op.create_table('ranking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('methodology', sa.String(length=32), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=True),
    sa.Column('sport_id', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['discipline.id'], ),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'methodology', 'discipline_id', 'entity_id', 'as_of', name='uq_ranking_entry')
    )
    op.create_index(op.f('ix_ranking_discipline_id'), 'ranking', ['discipline_id'], unique=False)
    op.create_index('ix_ranking_ladder', 'ranking', ['scope', 'methodology', 'discipline_id', 'as_of'], unique=False)
    op.create_index(op.f('ix_ranking_rank'), 'ranking', ['rank'], unique=False)
    op.create_index(op.f('ix_ranking_sport_id'), 'ranking', ['sport_id'], unique=False)
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=4), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=160), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('value_kind', sa.String(length=16), nullable=False),
    sa.Column('value_num', sa.Float(), nullable=True),
    sa.Column('value_text', sa.String(length=64), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('set_on', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('edition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['discipline_id'], ['discipline.id'], ),
    sa.ForeignKeyConstraint(['edition_id'], ['competition_edition.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_athlete_id'), 'record', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_record_country_id'), 'record', ['country_id'], unique=False)
    op.create_index(op.f('ix_record_discipline_id'), 'record', ['discipline_id'], unique=False)
    op.create_index(op.f('ix_record_edition_id'), 'record', ['edition_id'], unique=False)
    op.create_index(op.f('ix_record_kind'), 'record', ['kind'], unique=False)
    op.create_index('ix_record_lookup', 'record', ['kind', 'discipline_id', 'gender'], unique=False)
    op.create_index(op.f('ix_record_team_id'), 'record', ['team_id'], unique=False)
    op.create_table('medal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('discipline_id', sa.Integer(), nullable=True),
    sa.Column('event_name', sa.String(length=160), nullable=False),
    sa.Column('metal', sa.String(length=8), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['discipline_id'], ['discipline.id'], ),
    sa.ForeignKeyConstraint(['edition_id'], ['competition_edition.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medal_athlete_id'), 'medal', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_medal_country_id'), 'medal', ['country_id'], unique=False)
    op.create_index('ix_medal_edition_country', 'medal', ['edition_id', 'country_id'], unique=False)
    op.create_index(op.f('ix_medal_edition_id'), 'medal', ['edition_id'], unique=False)
    op.create_index(op.f('ix_medal_event_id'), 'medal', ['event_id'], unique=False)
    op.create_index(op.f('ix_medal_metal'), 'medal', ['metal'], unique=False)
    op.create_index(op.f('ix_medal_team_id'), 'medal', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medal_team_id'), table_name='medal')
    op.drop_index(op.f('ix_medal_metal'), table_name='medal')
    op.drop_index(op.f('ix_medal_event_id'), table_name='medal')
    op.drop_index(op.f('ix_medal_edition_id'), table_name='medal')
    op.drop_index('ix_medal_edition_country', table_name='medal')
    op.drop_index(op.f('ix_medal_country_id'), table_name='medal')
    op.drop_index(op.f('ix_medal_athlete_id'), table_name='medal')
    op.drop_table('medal')
    op.drop_index(op.f('ix_record_team_id'), table_name='record')
    op.drop_index('ix_record_lookup', table_name='record')
    op.drop_index(op.f('ix_record_kind'), table_name='record')
    op.drop_index(op.f('ix_record_edition_id'), table_name='record')
    op.drop_index(op.f('ix_record_discipline_id'), table_name='record')
    op.drop_index(op.f('ix_record_country_id'), table_name='record')
    op.drop_index(op.f('ix_record_athlete_id'), table_name='record')
    op.drop_table('record')
    op.drop_index(op.f('ix_ranking_sport_id'), table_name='ranking')
    op.drop_index(op.f('ix_ranking_rank'), table_name='ranking')
    op.drop_index('ix_ranking_ladder', table_name='ranking')
    op.drop_index(op.f('ix_ranking_discipline_id'), table_name='ranking')
    op.drop_table('ranking')
    op.drop_index(op.f('ix_venue_country_id'), table_name='venue')
    op.drop_table('venue')
    op.drop_index(op.f('ix_team_sport_id'), table_name='team')
    op.drop_index(op.f('ix_team_country_id'), table_name='team')
    op.drop_table('team')
    # ### end Alembic commands ###
